fix NoClassDefFoundError: org/apache/hadoop/shaded/com/ctc/wstx/io/InputBootstrapper exclude hadoop-client-api 3.3.5 which is transitive dependency from orc-tools.